on:
  push: ~
  workflow_dispatch: ~

jobs:
  init:
    name: "Say hello"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: "Listes files"
        run: ls
